# InfluxDB timeseries database --
# This is meant to store training logs and system usage metrics
# usage: kubectl create -f pod-timeseries.yaml
apiVersion: v1
kind: Pod
metadata:
  name: vogels-timeseries
  labels:
    name: vogels-timeseries
spec:
  containers:
    - name: influxdb
      image: influxdb
      ports:
      - containerPort: 8086
        name: http
      volumeMounts:
      - mountPath: /var/lib/influxdb
        name: db-data
        subPath: vogels/databases/timeseries-influxdb
  volumes:
  - name: db-data
    persistentVolumeClaim:
      claimName: mlo-scratch