# InfluxDB timeseries database --
# This is meant to store training logs and system usage metrics
# usage: kubectl create -f pod-timeseries.yaml
apiVersion: v1
kind: Pod
metadata:
  name: vogels-timeseries
  labels:
    name: vogels-timeseries
spec:
  containers:
    - name: influxdb
      image: influxdb:1.7
      ports:
      - containerPort: 8086
        name: api
      volumeMounts:
      - mountPath: /var/lib/influxdb
        name: mlo-scratch
        subPath: vogels/databases/timeseries-influxdb
  volumes:
  - name: mlo-scratch
    persistentVolumeClaim:
      claimName: mlo-scratch
