# InfluxDB timeseries database --
# This 'service' makes sure the open ports in the corresponding 'pod' are accessible.
# usage: kubectl create -f svc-timeseries.yaml
apiVersion: v1
kind: Service
metadata:
  name: vogels-timeseries
spec:
  type: NodePort
  ports:
  - name: http
    port: 8086
    protocol: TCP
  selector:
    name: vogels-timeseries
