user:
  name: GENERATOR_USERNAME
  id: GENERATOR_USERID
  group_id: GENERATOR_GROUPID

ports:
  frontend: GENERATOR_FRONTEND_PORT
  graphql: GENERATOR_GRAPHQL_PORT
  metadata: GENERATOR_METADATA_PORT
  timeseries: GENERATOR_TIMESERIES_PORT