# Copy this file as `config.yaml` and update the fields
user:
  name: GENERATOR_USERNAME
  id: GENERATOR_USERID
  group_id: GENERATOR_GROUPID

# Replace ? by {?=0: Thijs, ?=1: Andreas, ?=2: JB, ?=3: Ali,   others available}
ports:
  frontend: 30?05
  graphql: 30?04
  metadata: 30?17
  timeseries: 30?86
  timeseries_rcp: 30?88
