# InfluxDB job-metadata database --
# This is meant to store training logs and system usage metrics
# usage: kubectl create -f pod-metadata.yaml
apiVersion: v1
kind: Pod
metadata:
  name: vogels-graphql
  labels:
    name: vogels-graphql
spec:
  containers:
    - name: graphql
      image: ic-registry.epfl.ch/mlo/vogels_graphql
      ports:
      - containerPort: 4000
      volumeMounts:
        - mountPath: /scratch
          name: mlo-scratch
          subPath: vogels
  volumes:
  - name: mlo-scratch
    persistentVolumeClaim:
      claimName: mlo-scratch
