# InfluxDB job-metadata database --
# This 'service' makes sure the open ports in the corresponding 'pod' are accessible.
# usage: kubectl create -f svc-metadata.yaml
apiVersion: v1
kind: Service
metadata:
  name: vogels-graphql
  labels:
    user: vogels
spec:
  type: NodePort
  ports:
  - name: http
    targetPort: 4000
    port: 4000
    nodePort: 30004
    protocol: TCP
  selector:
    name: vogels-graphql
