# InfluxDB job-metadata database --
# This is meant to store training logs and system usage metrics
# usage: kubectl create -f pod-metadata.yaml
apiVersion: v1
kind: Pod
metadata:
  name: {{user.name}}-graphql
  labels:
    name: {{user.name}}-graphql
    user: {{user.name}}
spec:
  securityContext:
    runAsUser: 145554
    fsGroup: 11169
  containers:
    - name: graphql
      image: ic-registry.epfl.ch/mlo/{{user.name}}_graphql
      ports:
      - containerPort: 4000
      env:
        - {name: DATA,                     value: /data/{{user.name}}}
        - {name: JOBMONITOR_RESULTS_DIR,   value: /data/{{user.name}}/results}
      volumeMounts:
        - mountPath: /scratch
          name: mlo-scratch
          subPath: {{user.name}}
        - mountPath: /data
          name: mlodata1
  volumes:
  - name: mlo-scratch
    persistentVolumeClaim:
      claimName: mlo-scratch
  - name: mlodata1
    persistentVolumeClaim:
      claimName: pv-mlodata1
