"""
NOTE:    This file has automatically been generated.
         Datetime: {{now}}
"""
apiVersion: v1
kind: Service
metadata:
  name: {{user.name}}-graphql
  labels:
    user: {{user.name}}
spec:
  type: NodePort
  ports:
  - name: http
    targetPort: 4000
    port: 4000
    nodePort: {{ports.graphql}}
    protocol: TCP
  selector:
    name: {{user.name}}-graphql
