# InfluxDB job-metadata database --
# This is meant to store training logs and system usage metrics
# usage: kubectl create -f pod-metadata.yaml
apiVersion: v1
kind: Pod
metadata:
  name: vogels-metadata
  labels:
    name: vogels-metadata
    user: vogels
spec:
  securityContext:
    runAsUser: 145554
    fsGroup: 11169
  containers:
    - name: mongo
      image: mongo:4.0
      ports:
      - containerPort: 27017
        name: http
      volumeMounts:
      - mountPath: /data/db
        name: data
  volumes:
  - name: data
    persistentVolumeClaim:
      claimName: pv-mlodata1-vogels-databases-job-metadata-mongodb
