---
apiVersion: v1
kind: Service
metadata:
  name: metadata
  labels:
    name: metadata
spec:
  type: NodePort
  ports:
    - name: http
      port: 27017
      nodePort: 30017
      protocol: TCP
  selector:
    name: metadata
---
apiVersion: v1
kind: Pod
metadata:
  name: metadata
  labels:
    name: metadata
spec:
  nodeSelector:
    hardware-type: CPUONLY
  securityContext:
    runAsUser: 145554
    fsGroup: 11169
  containers:
    - name: mongo
      image: mongo:4.0
      ports:
        - containerPort: 27017
          name: http
      volumeMounts:
        - mountPath: /data/db
          name: data
  volumes:
  - name: data
    persistentVolumeClaim:
      claimName: pv-mlodata1-vogels-databases-job-metadata-mongodb
