---
apiVersion: v1
kind: Service
metadata:
  name: timeseries
  labels:
    name: timeseries
spec:
  type: NodePort
  ports:
    - name: http
      port: 8086
      nodePort: 30086
      protocol: TCP
    - name: rcp
      port: 8088
      nodePort: 30088
      protocol: TCP
  selector:
    name: timeseries
---
apiVersion: v1
kind: Pod
metadata:
  name: timeseries
  labels:
    name: timeseries
spec:
  nodeSelector:
      hardware-type: CPUONLY
  securityContext:
    runAsUser: 145554
    fsGroup: 11169
  containers:
    - name: influxdb
      image: influxdb:1.7-alpine
      ports:
        - containerPort: 8086
          name: api
        - containerPort: 8088
          name: rcp
      volumeMounts:
        - mountPath: /var/lib/influxdb
          name: data
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: pv-mlodata1-vogels-databases-timeseries-influxdb
