# InfluxDB timeseries database --
# This is meant to store training logs and system usage metrics
# usage: kubectl create -f pod-timeseries.yaml
apiVersion: v1
kind: Pod
metadata:
  name: {{user.name}}-timeseries
  labels:
    name: {{user.name}}-timeseries
    user: {{user.name}}
spec:
  securityContext:
    runAsUser: {{user.id}}
    fsGroup: {{user.group_id}}
  containers:
    - name: influxdb
      image: influxdb:1.7-alpine
      ports:
      - containerPort: 8086
        name: api
      volumeMounts:
      - mountPath: /var/lib/influxdb
        name: data
  volumes:
  - name: data
    persistentVolumeClaim:
      claimName: pv-mlodata1-{{user.name}}-databases-timeseries-influxdb
