#
# NOTE:    This file has automatically been generated.
#          Datetime: {{now}}
#
apiVersion: v1
kind: Pod
metadata:
  name: {{user.name}}-timeseries
  labels:
    name: {{user.name}}-timeseries
    user: {{user.name}}
spec:
  nodeSelector:
      hardware-type: CPUONLY
  securityContext:
    runAsUser: {{user.id}}
    fsGroup: {{user.group_id}}
  containers:
    - name: influxdb
      image: influxdb:1.7-alpine
      ports:
      - containerPort: 8086
        name: api
      - containerPort: 8088
        name: rcp
      volumeMounts:
      - mountPath: /var/lib/influxdb
        name: data
  volumes:
  - name: data
    persistentVolumeClaim:
      claimName: pv-mlodata1-{{user.name}}-databases-timeseries-influxdb
