# InfluxDB timeseries database --
# This 'service' makes sure the open ports in the corresponding 'pod' are accessible.
# usage: kubectl create -f svc-timeseries.yaml
apiVersion: v1
kind: Service
metadata:
  name: {{user.name}}-timeseries
  labels:
    name: {{user.name}}-timeseries
    user: {{user.name}}
spec:
  type: NodePort
  ports:
  - name: http
    port: 8086
    nodePort: {{ports.timeseries}}
    protocol: TCP
  selector:
    name: {{user.name}}-timeseries
