#
# NOTE:    This file has automatically been generated.
#          Datetime: {{now}}
#
apiVersion: v1
kind: Service
metadata:
  name: {{user.name}}-timeseries
  labels:
    name: {{user.name}}-timeseries
    user: {{user.name}}
spec:
  type: NodePort
  ports:
  - name: http
    port: 8086
    nodePort: {{ports.timeseries}}
    protocol: TCP
  - name: rcp
    port: 8088
    nodePort: {{ports.timeseries_rcp}}
    protocol: TCP
  selector:
    name: {{user.name}}-timeseries
